import Head from 'next/head'
import Dashboard from '../components/Dashboard'

export default function Home() {

  return (
    <Dashboard className=''>
      <Head>
        <title>Portfolio Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        This is the main Dashboard!
      </main>
    </Dashboard>
  )
}
